meta_product_name: "cBreeze"
meta_title: "cBreeze - Plan your kite week with ease"
meta_description: "Plan your kite week with ease"
meta_image: "banner2.jpg"                       # should exist in `app/assets/images/`
