meta_product_name: "cBreeze"
meta_title: "cBreeze - Plan your kite week with ease"
meta_description: "Never miss epic conditions"
meta_image: "fb_banner.jpg"                       # should exist in `app/assets/images/`
